version: '3.8' # Use the appropriate version of Docker Compose

services:
  postgres:
    image: postgres:latest # You can specify a specific PostgreSQL version if needed
    container_name: postgresql # Give your container a name
    environment:
      POSTGRES_DB: development # Replace with your desired database name
      POSTGRES_USER: service_user # Replace with your desired username
      POSTGRES_PASSWORD: 123456 # Replace with your desired password
    ports:
      - '5432:5432' # Map host port to container port (change as needed)
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persist data to a Docker volume

volumes:
  postgres-data: # Define a named volume for data persistence
